name: Force Sync from Upstream

on:
  schedule:
    - cron: "50 6 * * *"   # UTC 06:50 ≈ 美西 23:50（夏令时）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add or update upstream
        run: |
          git remote | grep -q "^upstream$" || git remote add upstream https://github.com/feijiqun/feijiqun.github.io.git
          git fetch upstream --tags

      - name: Fast-forward merge from upstream/main
        run: |
          git checkout main
          # 仅快进合并，避免覆盖你自己的文件（包括工作流）
          git merge --ff-only upstream/main

      - name: Push to your fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
          git push origin --tags
